### PR TITLE
fix URL typo

### PR DESCRIPTION
**Pull request by petar-i-todorov**

### CODE REVIEW

**Comment by jlengstorf** [comment]
Thanks for this, @petardotjs! It looks like the formatter in your IDE got hold of this, though, and changed a bunch of other things beside the URL — would you mind undoing those changes before I merge?

Thanks again!

**Comment by petar-i-todorov** [comment]
Fixed it (hopefully). I saw that issue instantly but since it was my first pull request, didn't know that I could change it. Sorry about that.

**Review by jlengstorf — APPROVED** [review]
thanks so much!

**Comment by jlengstorf** [comment]
@all-contributors please add @petardotjs for code

**Pull request merged**
